### ISSUE TITLE
Erro ao realizar o download dos links

### ISSUE THREAD

**Issue by absantiago** [rafaelnovello/news-categ-demo#1]
Bom dia Rafael,
O código que eu executei para fazer o download dos links foi:
**python news_categorizer.py -f links.csv -t base.pkl**

Com isso o python me retornou a seguinte mensagem de erro:

ERROR:root:Length mismatch: Expected axis has 0 elements, new values have 3 elements
Traceback (most recent call last):
  File "news_categorizer.py", line 156, in <module>
    main(links_file, fit_file, to_predict)
  File "news_categorizer.py", line 103, in main
    df = prepare_data(links_file)
  File "news_categorizer.py", line 124, in prepare_data
    df.columns = ['link', 'categoria', 'texto']
  File "C:\Users\absantiago\AppData\Local\Continuum\anaconda3\envs\testeConda\lib\site-packages\pandas\core\generic.py", line 2757, in __setattr__
    return object.__setattr__(self, name, value)
  File "pandas\src\properties.pyx", line 65, in pandas.lib.AxisProperty.__set__ (pandas\lib.c:46249)
  File "C:\Users\absantiago\AppData\Local\Continuum\anaconda3\envs\testeConda\lib\site-packages\pandas\core\generic.py", line 448, in _set_axis
    self._data.set_axis(axis, labels)
  File "C:\Users\absantiago\AppData\Local\Continuum\anaconda3\envs\testeConda\lib\site-packages\pandas\core\internals.py", line 2802, in set_axis
    (old_len, new_len))
ValueError: Length mismatch: Expected axis has 0 elements, new values have 3 elements
error:root:Length mismatch: Expected axis has 0 elements, new values have 3 elementsTraceback (most recent call last):  File "news_categorizer.py", line 156, in <module>    main(links_file, fit_file, to_predict)  File "news_categorizer.py", line 103, in main    df = prepare_data(links_file)  File "news_categorizer.py", line 124, in prepare_data    df.columns = ['link', 'categoria', 'texto']  File "C:\Users\absantiago\AppData\Local\Continuum\anaconda3\envs\testeConda\lib\site-packages\pandas\core\generic.py", line 2757, in __setattr__    return object.__setattr__(self, name, value)  File "pandas\src\properties.pyx", line 65, in pandas.lib.AxisProperty.__set__ (pandas\lib.c:46249)  File "C:\Users\absantiago\AppData\Local\Continuum\anaconda3\envs\testeConda\lib\site-packages\pandas\core\generic.py", line 448, in _set_axis    self._data.set_axis(axis, labels)  File "C:\Users\absantiago\AppData\Local\Continuum\anaconda3\envs\testeConda\lib\site-packages\pandas\core\internals.py", line 2802, in set_axis    (old_len, new_len))ValueError: Length mismatch: Expected axis has 0 elements, new values have 3 elements

Desde já agradeço sua atenção.

**Comment by mbressan06** [comment]
Olá!!
Estou com um erro similar com a mesma origem

```
ERROR:root:Length mismatch: Expected axis has 0 elements, new values have 3 elements
Traceback (most recent call last):
  File "news_categorizer.py", line 172, in <module>
    main(links_file, fit_file, to_predict)
  File "news_categorizer.py", line 118, in main
    df = prepare_data(links_file)
  File "news_categorizer.py", line 139, in prepare_data
    df.columns = ['link', 'categoria', 'texto']
  File "C:\Python27\lib\site-packages\pandas\core\generic.py", line 3627, in __setattr__
    return object.__setattr__(self, name, value)
  File "pandas\_libs\properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "C:\Python27\lib\site-packages\pandas\core\generic.py", line 559, in _set_axis
    self._data.set_axis(axis, labels)
  File "C:\Python27\lib\site-packages\pandas\core\internals.py", line 3074, in set_axis
    (old_len, new_len))
ValueError: Length mismatch: Expected axis has 0 elements, new values have 3 elements
```

Tem alguma idéia de como resolver isso?

**Comment by mbressan06** [comment]
@absantiago consegui evoluir alem deste erro.

Você precisa iniciar o NLTK Downloader e baixar todos os dados de que precisa o script.
Abra um console do Python e faça o seguinte:

```
>>> import nltk
>>> nltk.download ()
```

Na janela que se abre, basta pressionar o botão 'Download' para baixar todos os recursos _corpora_ .
